'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ViewsService

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", ConfigurationName:="ViewsService.ViewsSoap")> _
    Public Interface ViewsSoap

        'CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/GetView", ReplyAction:="*")> _
        Function GetView(ByVal request As ViewsService.GetViewRequest) As ViewsService.GetViewResponse

        'CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/GetViewHtml", ReplyAction:="*")> _
        Function GetViewHtml(ByVal request As ViewsService.GetViewHtmlRequest) As ViewsService.GetViewHtmlResponse

        'CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/DeleteView", ReplyAction:="*")> _
        Function DeleteView(ByVal request As ViewsService.DeleteViewRequest) As ViewsService.DeleteViewResponse

        'CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/AddView", ReplyAction:="*")> _
        Function AddView(ByVal request As ViewsService.AddViewRequest) As ViewsService.AddViewResponse

        'CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/GetViewCollection", ReplyAction:="*")> _
        Function GetViewCollection(ByVal request As ViewsService.GetViewCollectionRequest) As ViewsService.GetViewCollectionResponse

        'CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/UpdateView", ReplyAction:="*")> _
        Function UpdateView(ByVal request As ViewsService.UpdateViewRequest) As ViewsService.UpdateViewResponse

        'CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/UpdateViewHtml", ReplyAction:="*")> _
        Function UpdateViewHtml(ByVal request As ViewsService.UpdateViewHtmlRequest) As ViewsService.UpdateViewHtmlResponse

        'CODEGEN: Generating message contract since element name listName from namespace http://schemas.microsoft.com/sharepoint/soap/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://schemas.microsoft.com/sharepoint/soap/UpdateViewHtml2", ReplyAction:="*")> _
        Function UpdateViewHtml2(ByVal request As ViewsService.UpdateViewHtml2Request) As ViewsService.UpdateViewHtml2Response
    End Interface

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class GetViewRequest

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetView", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)> _
        Public Body As ViewsService.GetViewRequestBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As ViewsService.GetViewRequestBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")> _
    Partial Public Class GetViewRequestBody

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=0)> _
        Public listName As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=1)> _
        Public viewName As String

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal listName As String, ByVal viewName As String)
            MyBase.New()
            Me.listName = listName
            Me.viewName = viewName
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class GetViewResponse

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetViewResponse", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)> _
        Public Body As ViewsService.GetViewResponseBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As ViewsService.GetViewResponseBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")> _
    Partial Public Class GetViewResponseBody

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=0)> _
        Public GetViewResult As System.Xml.Linq.XElement

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal GetViewResult As System.Xml.Linq.XElement)
            MyBase.New()
            Me.GetViewResult = GetViewResult
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class GetViewHtmlRequest

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetViewHtml", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)> _
        Public Body As ViewsService.GetViewHtmlRequestBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As ViewsService.GetViewHtmlRequestBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")> _
    Partial Public Class GetViewHtmlRequestBody

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=0)> _
        Public listName As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=1)> _
        Public viewName As String

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal listName As String, ByVal viewName As String)
            MyBase.New()
            Me.listName = listName
            Me.viewName = viewName
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class GetViewHtmlResponse

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetViewHtmlResponse", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)> _
        Public Body As ViewsService.GetViewHtmlResponseBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As ViewsService.GetViewHtmlResponseBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")> _
    Partial Public Class GetViewHtmlResponseBody

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=0)> _
        Public GetViewHtmlResult As System.Xml.Linq.XElement

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal GetViewHtmlResult As System.Xml.Linq.XElement)
            MyBase.New()
            Me.GetViewHtmlResult = GetViewHtmlResult
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class DeleteViewRequest

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DeleteView", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)> _
        Public Body As ViewsService.DeleteViewRequestBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As ViewsService.DeleteViewRequestBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")> _
    Partial Public Class DeleteViewRequestBody

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=0)> _
        Public listName As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=1)> _
        Public viewName As String

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal listName As String, ByVal viewName As String)
            MyBase.New()
            Me.listName = listName
            Me.viewName = viewName
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class DeleteViewResponse

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="DeleteViewResponse", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)> _
        Public Body As ViewsService.DeleteViewResponseBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As ViewsService.DeleteViewResponseBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute()> _
    Partial Public Class DeleteViewResponseBody

        Public Sub New()
            MyBase.New()
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class AddViewRequest

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AddView", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)> _
        Public Body As ViewsService.AddViewRequestBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As ViewsService.AddViewRequestBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")> _
    Partial Public Class AddViewRequestBody

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=0)> _
        Public listName As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=1)> _
        Public viewName As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=2)> _
        Public viewFields As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=3)> _
        Public query As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=4)> _
        Public rowLimit As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=5)> _
        Public type As String

        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)> _
        Public makeViewDefault As Boolean

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal listName As String, ByVal viewName As String, ByVal viewFields As System.Xml.Linq.XElement, ByVal query As System.Xml.Linq.XElement, ByVal rowLimit As System.Xml.Linq.XElement, ByVal type As String, ByVal makeViewDefault As Boolean)
            MyBase.New()
            Me.listName = listName
            Me.viewName = viewName
            Me.viewFields = viewFields
            Me.query = query
            Me.rowLimit = rowLimit
            Me.type = type
            Me.makeViewDefault = makeViewDefault
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class AddViewResponse

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AddViewResponse", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)> _
        Public Body As ViewsService.AddViewResponseBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As ViewsService.AddViewResponseBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")> _
    Partial Public Class AddViewResponseBody

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=0)> _
        Public AddViewResult As System.Xml.Linq.XElement

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal AddViewResult As System.Xml.Linq.XElement)
            MyBase.New()
            Me.AddViewResult = AddViewResult
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class GetViewCollectionRequest

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetViewCollection", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)> _
        Public Body As ViewsService.GetViewCollectionRequestBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As ViewsService.GetViewCollectionRequestBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")> _
    Partial Public Class GetViewCollectionRequestBody

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=0)> _
        Public listName As String

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal listName As String)
            MyBase.New()
            Me.listName = listName
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class GetViewCollectionResponse

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetViewCollectionResponse", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)> _
        Public Body As ViewsService.GetViewCollectionResponseBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As ViewsService.GetViewCollectionResponseBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")> _
    Partial Public Class GetViewCollectionResponseBody

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=0)> _
        Public GetViewCollectionResult As System.Xml.Linq.XElement

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal GetViewCollectionResult As System.Xml.Linq.XElement)
            MyBase.New()
            Me.GetViewCollectionResult = GetViewCollectionResult
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class UpdateViewRequest

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateView", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)> _
        Public Body As ViewsService.UpdateViewRequestBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As ViewsService.UpdateViewRequestBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")> _
    Partial Public Class UpdateViewRequestBody

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=0)> _
        Public listName As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=1)> _
        Public viewName As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=2)> _
        Public viewProperties As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=3)> _
        Public query As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=4)> _
        Public viewFields As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=5)> _
        Public aggregations As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=6)> _
        Public formats As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=7)> _
        Public rowLimit As System.Xml.Linq.XElement

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal listName As String, ByVal viewName As String, ByVal viewProperties As System.Xml.Linq.XElement, ByVal query As System.Xml.Linq.XElement, ByVal viewFields As System.Xml.Linq.XElement, ByVal aggregations As System.Xml.Linq.XElement, ByVal formats As System.Xml.Linq.XElement, ByVal rowLimit As System.Xml.Linq.XElement)
            MyBase.New()
            Me.listName = listName
            Me.viewName = viewName
            Me.viewProperties = viewProperties
            Me.query = query
            Me.viewFields = viewFields
            Me.aggregations = aggregations
            Me.formats = formats
            Me.rowLimit = rowLimit
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class UpdateViewResponse

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateViewResponse", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)> _
        Public Body As ViewsService.UpdateViewResponseBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As ViewsService.UpdateViewResponseBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")> _
    Partial Public Class UpdateViewResponseBody

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=0)> _
        Public UpdateViewResult As System.Xml.Linq.XElement

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal UpdateViewResult As System.Xml.Linq.XElement)
            MyBase.New()
            Me.UpdateViewResult = UpdateViewResult
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class UpdateViewHtmlRequest

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateViewHtml", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)> _
        Public Body As ViewsService.UpdateViewHtmlRequestBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As ViewsService.UpdateViewHtmlRequestBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")> _
    Partial Public Class UpdateViewHtmlRequestBody

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=0)> _
        Public listName As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=1)> _
        Public viewName As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=2)> _
        Public viewProperties As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=3)> _
        Public toolbar As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=4)> _
        Public viewHeader As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=5)> _
        Public viewBody As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=6)> _
        Public viewFooter As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=7)> _
        Public viewEmpty As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=8)> _
        Public rowLimitExceeded As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=9)> _
        Public query As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=10)> _
        Public viewFields As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=11)> _
        Public aggregations As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=12)> _
        Public formats As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=13)> _
        Public rowLimit As System.Xml.Linq.XElement

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal listName As String, ByVal viewName As String, ByVal viewProperties As System.Xml.Linq.XElement, ByVal toolbar As System.Xml.Linq.XElement, ByVal viewHeader As System.Xml.Linq.XElement, ByVal viewBody As System.Xml.Linq.XElement, ByVal viewFooter As System.Xml.Linq.XElement, ByVal viewEmpty As System.Xml.Linq.XElement, ByVal rowLimitExceeded As System.Xml.Linq.XElement, ByVal query As System.Xml.Linq.XElement, ByVal viewFields As System.Xml.Linq.XElement, ByVal aggregations As System.Xml.Linq.XElement, ByVal formats As System.Xml.Linq.XElement, ByVal rowLimit As System.Xml.Linq.XElement)
            MyBase.New()
            Me.listName = listName
            Me.viewName = viewName
            Me.viewProperties = viewProperties
            Me.toolbar = toolbar
            Me.viewHeader = viewHeader
            Me.viewBody = viewBody
            Me.viewFooter = viewFooter
            Me.viewEmpty = viewEmpty
            Me.rowLimitExceeded = rowLimitExceeded
            Me.query = query
            Me.viewFields = viewFields
            Me.aggregations = aggregations
            Me.formats = formats
            Me.rowLimit = rowLimit
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class UpdateViewHtmlResponse

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateViewHtmlResponse", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)> _
        Public Body As ViewsService.UpdateViewHtmlResponseBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As ViewsService.UpdateViewHtmlResponseBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")> _
    Partial Public Class UpdateViewHtmlResponseBody

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=0)> _
        Public UpdateViewHtmlResult As System.Xml.Linq.XElement

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal UpdateViewHtmlResult As System.Xml.Linq.XElement)
            MyBase.New()
            Me.UpdateViewHtmlResult = UpdateViewHtmlResult
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class UpdateViewHtml2Request

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateViewHtml2", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)> _
        Public Body As ViewsService.UpdateViewHtml2RequestBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As ViewsService.UpdateViewHtml2RequestBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")> _
    Partial Public Class UpdateViewHtml2RequestBody

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=0)> _
        Public listName As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=1)> _
        Public viewName As String

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=2)> _
        Public viewProperties As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=3)> _
        Public toolbar As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=4)> _
        Public viewHeader As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=5)> _
        Public viewBody As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=6)> _
        Public viewFooter As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=7)> _
        Public viewEmpty As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=8)> _
        Public rowLimitExceeded As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=9)> _
        Public query As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=10)> _
        Public viewFields As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=11)> _
        Public aggregations As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=12)> _
        Public formats As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=13)> _
        Public rowLimit As System.Xml.Linq.XElement

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=14)> _
        Public openApplicationExtension As String

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal listName As String, ByVal viewName As String, ByVal viewProperties As System.Xml.Linq.XElement, ByVal toolbar As System.Xml.Linq.XElement, ByVal viewHeader As System.Xml.Linq.XElement, ByVal viewBody As System.Xml.Linq.XElement, ByVal viewFooter As System.Xml.Linq.XElement, ByVal viewEmpty As System.Xml.Linq.XElement, ByVal rowLimitExceeded As System.Xml.Linq.XElement, ByVal query As System.Xml.Linq.XElement, ByVal viewFields As System.Xml.Linq.XElement, ByVal aggregations As System.Xml.Linq.XElement, ByVal formats As System.Xml.Linq.XElement, ByVal rowLimit As System.Xml.Linq.XElement, ByVal openApplicationExtension As String)
            MyBase.New()
            Me.listName = listName
            Me.viewName = viewName
            Me.viewProperties = viewProperties
            Me.toolbar = toolbar
            Me.viewHeader = viewHeader
            Me.viewBody = viewBody
            Me.viewFooter = viewFooter
            Me.viewEmpty = viewEmpty
            Me.rowLimitExceeded = rowLimitExceeded
            Me.query = query
            Me.viewFields = viewFields
            Me.aggregations = aggregations
            Me.formats = formats
            Me.rowLimit = rowLimit
            Me.openApplicationExtension = openApplicationExtension
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=False)> _
    Partial Public Class UpdateViewHtml2Response

        <System.ServiceModel.MessageBodyMemberAttribute(Name:="UpdateViewHtml2Response", [Namespace]:="http://schemas.microsoft.com/sharepoint/soap/", Order:=0)> _
        Public Body As ViewsService.UpdateViewHtml2ResponseBody

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal Body As ViewsService.UpdateViewHtml2ResponseBody)
            MyBase.New()
            Me.Body = Body
        End Sub
    End Class

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://schemas.microsoft.com/sharepoint/soap/")> _
    Partial Public Class UpdateViewHtml2ResponseBody

        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=False, Order:=0)> _
        Public UpdateViewHtml2Result As System.Xml.Linq.XElement

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal UpdateViewHtml2Result As System.Xml.Linq.XElement)
            MyBase.New()
            Me.UpdateViewHtml2Result = UpdateViewHtml2Result
        End Sub
    End Class

    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
    Public Interface ViewsSoapChannel
        Inherits ViewsService.ViewsSoap, System.ServiceModel.IClientChannel
    End Interface

    <System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
    Partial Public Class ViewsSoapClient
        Inherits System.ServiceModel.ClientBase(Of ViewsService.ViewsSoap)
        Implements ViewsService.ViewsSoap

        Public Sub New()
            MyBase.New()
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub

        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function ViewsService_ViewsSoap_GetView(ByVal request As ViewsService.GetViewRequest) As ViewsService.GetViewResponse Implements ViewsService.ViewsSoap.GetView
            Return MyBase.Channel.GetView(request)
        End Function

        Public Function GetView(ByVal listName As String, ByVal viewName As String) As System.Xml.Linq.XElement
            Dim inValue As ViewsService.GetViewRequest = New ViewsService.GetViewRequest
            inValue.Body = New ViewsService.GetViewRequestBody
            inValue.Body.listName = listName
            inValue.Body.viewName = viewName
            Dim retVal As ViewsService.GetViewResponse = CType(Me, ViewsService.ViewsSoap).GetView(inValue)
            Return retVal.Body.GetViewResult
        End Function

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function ViewsService_ViewsSoap_GetViewHtml(ByVal request As ViewsService.GetViewHtmlRequest) As ViewsService.GetViewHtmlResponse Implements ViewsService.ViewsSoap.GetViewHtml
            Return MyBase.Channel.GetViewHtml(request)
        End Function

        Public Function GetViewHtml(ByVal listName As String, ByVal viewName As String) As System.Xml.Linq.XElement
            Dim inValue As ViewsService.GetViewHtmlRequest = New ViewsService.GetViewHtmlRequest
            inValue.Body = New ViewsService.GetViewHtmlRequestBody
            inValue.Body.listName = listName
            inValue.Body.viewName = viewName
            Dim retVal As ViewsService.GetViewHtmlResponse = CType(Me, ViewsService.ViewsSoap).GetViewHtml(inValue)
            Return retVal.Body.GetViewHtmlResult
        End Function

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function ViewsService_ViewsSoap_DeleteView(ByVal request As ViewsService.DeleteViewRequest) As ViewsService.DeleteViewResponse Implements ViewsService.ViewsSoap.DeleteView
            Return MyBase.Channel.DeleteView(request)
        End Function

        Public Sub DeleteView(ByVal listName As String, ByVal viewName As String)
            Dim inValue As ViewsService.DeleteViewRequest = New ViewsService.DeleteViewRequest
            inValue.Body = New ViewsService.DeleteViewRequestBody
            inValue.Body.listName = listName
            inValue.Body.viewName = viewName
            Dim retVal As ViewsService.DeleteViewResponse = CType(Me, ViewsService.ViewsSoap).DeleteView(inValue)
        End Sub

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function ViewsService_ViewsSoap_AddView(ByVal request As ViewsService.AddViewRequest) As ViewsService.AddViewResponse Implements ViewsService.ViewsSoap.AddView
            Return MyBase.Channel.AddView(request)
        End Function

        Public Function AddView(ByVal listName As String, ByVal viewName As String, ByVal viewFields As System.Xml.Linq.XElement, ByVal query As System.Xml.Linq.XElement, ByVal rowLimit As System.Xml.Linq.XElement, ByVal type As String, ByVal makeViewDefault As Boolean) As System.Xml.Linq.XElement
            Dim inValue As ViewsService.AddViewRequest = New ViewsService.AddViewRequest
            inValue.Body = New ViewsService.AddViewRequestBody
            inValue.Body.listName = listName
            inValue.Body.viewName = viewName
            inValue.Body.viewFields = viewFields
            inValue.Body.query = query
            inValue.Body.rowLimit = rowLimit
            inValue.Body.type = type
            inValue.Body.makeViewDefault = makeViewDefault
            Dim retVal As ViewsService.AddViewResponse = CType(Me, ViewsService.ViewsSoap).AddView(inValue)
            Return retVal.Body.AddViewResult
        End Function

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function ViewsService_ViewsSoap_GetViewCollection(ByVal request As ViewsService.GetViewCollectionRequest) As ViewsService.GetViewCollectionResponse Implements ViewsService.ViewsSoap.GetViewCollection
            Return MyBase.Channel.GetViewCollection(request)
        End Function

        Public Function GetViewCollection(ByVal listName As String) As System.Xml.Linq.XElement
            Dim inValue As ViewsService.GetViewCollectionRequest = New ViewsService.GetViewCollectionRequest
            inValue.Body = New ViewsService.GetViewCollectionRequestBody
            inValue.Body.listName = listName
            Dim retVal As ViewsService.GetViewCollectionResponse = CType(Me, ViewsService.ViewsSoap).GetViewCollection(inValue)
            Return retVal.Body.GetViewCollectionResult
        End Function

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function ViewsService_ViewsSoap_UpdateView(ByVal request As ViewsService.UpdateViewRequest) As ViewsService.UpdateViewResponse Implements ViewsService.ViewsSoap.UpdateView
            Return MyBase.Channel.UpdateView(request)
        End Function

        Public Function UpdateView(ByVal listName As String, ByVal viewName As String, ByVal viewProperties As System.Xml.Linq.XElement, ByVal query As System.Xml.Linq.XElement, ByVal viewFields As System.Xml.Linq.XElement, ByVal aggregations As System.Xml.Linq.XElement, ByVal formats As System.Xml.Linq.XElement, ByVal rowLimit As System.Xml.Linq.XElement) As System.Xml.Linq.XElement
            Dim inValue As ViewsService.UpdateViewRequest = New ViewsService.UpdateViewRequest
            inValue.Body = New ViewsService.UpdateViewRequestBody
            inValue.Body.listName = listName
            inValue.Body.viewName = viewName
            inValue.Body.viewProperties = viewProperties
            inValue.Body.query = query
            inValue.Body.viewFields = viewFields
            inValue.Body.aggregations = aggregations
            inValue.Body.formats = formats
            inValue.Body.rowLimit = rowLimit
            Dim retVal As ViewsService.UpdateViewResponse = CType(Me, ViewsService.ViewsSoap).UpdateView(inValue)
            Return retVal.Body.UpdateViewResult
        End Function

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function ViewsService_ViewsSoap_UpdateViewHtml(ByVal request As ViewsService.UpdateViewHtmlRequest) As ViewsService.UpdateViewHtmlResponse Implements ViewsService.ViewsSoap.UpdateViewHtml
            Return MyBase.Channel.UpdateViewHtml(request)
        End Function

        Public Function UpdateViewHtml(ByVal listName As String, ByVal viewName As String, ByVal viewProperties As System.Xml.Linq.XElement, ByVal toolbar As System.Xml.Linq.XElement, ByVal viewHeader As System.Xml.Linq.XElement, ByVal viewBody As System.Xml.Linq.XElement, ByVal viewFooter As System.Xml.Linq.XElement, ByVal viewEmpty As System.Xml.Linq.XElement, ByVal rowLimitExceeded As System.Xml.Linq.XElement, ByVal query As System.Xml.Linq.XElement, ByVal viewFields As System.Xml.Linq.XElement, ByVal aggregations As System.Xml.Linq.XElement, ByVal formats As System.Xml.Linq.XElement, ByVal rowLimit As System.Xml.Linq.XElement) As System.Xml.Linq.XElement
            Dim inValue As ViewsService.UpdateViewHtmlRequest = New ViewsService.UpdateViewHtmlRequest
            inValue.Body = New ViewsService.UpdateViewHtmlRequestBody
            inValue.Body.listName = listName
            inValue.Body.viewName = viewName
            inValue.Body.viewProperties = viewProperties
            inValue.Body.toolbar = toolbar
            inValue.Body.viewHeader = viewHeader
            inValue.Body.viewBody = viewBody
            inValue.Body.viewFooter = viewFooter
            inValue.Body.viewEmpty = viewEmpty
            inValue.Body.rowLimitExceeded = rowLimitExceeded
            inValue.Body.query = query
            inValue.Body.viewFields = viewFields
            inValue.Body.aggregations = aggregations
            inValue.Body.formats = formats
            inValue.Body.rowLimit = rowLimit
            Dim retVal As ViewsService.UpdateViewHtmlResponse = CType(Me, ViewsService.ViewsSoap).UpdateViewHtml(inValue)
            Return retVal.Body.UpdateViewHtmlResult
        End Function

        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)> _
        Function ViewsService_ViewsSoap_UpdateViewHtml2(ByVal request As ViewsService.UpdateViewHtml2Request) As ViewsService.UpdateViewHtml2Response Implements ViewsService.ViewsSoap.UpdateViewHtml2
            Return MyBase.Channel.UpdateViewHtml2(request)
        End Function

        Public Function UpdateViewHtml2(ByVal listName As String, ByVal viewName As String, ByVal viewProperties As System.Xml.Linq.XElement, ByVal toolbar As System.Xml.Linq.XElement, ByVal viewHeader As System.Xml.Linq.XElement, ByVal viewBody As System.Xml.Linq.XElement, ByVal viewFooter As System.Xml.Linq.XElement, ByVal viewEmpty As System.Xml.Linq.XElement, ByVal rowLimitExceeded As System.Xml.Linq.XElement, ByVal query As System.Xml.Linq.XElement, ByVal viewFields As System.Xml.Linq.XElement, ByVal aggregations As System.Xml.Linq.XElement, ByVal formats As System.Xml.Linq.XElement, ByVal rowLimit As System.Xml.Linq.XElement, ByVal openApplicationExtension As String) As System.Xml.Linq.XElement
            Dim inValue As ViewsService.UpdateViewHtml2Request = New ViewsService.UpdateViewHtml2Request
            inValue.Body = New ViewsService.UpdateViewHtml2RequestBody
            inValue.Body.listName = listName
            inValue.Body.viewName = viewName
            inValue.Body.viewProperties = viewProperties
            inValue.Body.toolbar = toolbar
            inValue.Body.viewHeader = viewHeader
            inValue.Body.viewBody = viewBody
            inValue.Body.viewFooter = viewFooter
            inValue.Body.viewEmpty = viewEmpty
            inValue.Body.rowLimitExceeded = rowLimitExceeded
            inValue.Body.query = query
            inValue.Body.viewFields = viewFields
            inValue.Body.aggregations = aggregations
            inValue.Body.formats = formats
            inValue.Body.rowLimit = rowLimit
            inValue.Body.openApplicationExtension = openApplicationExtension
            Dim retVal As ViewsService.UpdateViewHtml2Response = CType(Me, ViewsService.ViewsSoap).UpdateViewHtml2(inValue)
            Return retVal.Body.UpdateViewHtml2Result
        End Function
    End Class
End Namespace
